---
- name: Set the path when you installed Xcode
  become: true
  become_method: sudo
  command: xcode-select -s /Applications/Xcode.app/Contents/Developer
  changed_when: false

- name: Accept xcode license
  become: true
  become_method: sudo
  command: xcodebuild -license accept
  changed_when: false

- name: Homebrew tap
  homebrew_tap:
    name: homebrew/cask-versions

- name: Homebrew tap
  homebrew_tap:
    name: denji/nginx
