---
- name: Homebrew tap
  homebrew_tap:
    name: homebrew/cask-versions

- name: Homebrew tap
  homebrew_tap:
    name: tenantcloud/tenantcloud

- name: Homebrew tap
  homebrew_tap:
    name: denji/nginx
