---
- name: Add mysql-client line in .zshrc file
  lineinfile:
    path: $HOME/.zshrc
    line: 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"'
    create: true
    state: present
    mode: 0644

- name: source zshrc
  command: /bin/zsh -c "source ~/.zshrc"
  changed_when: false
