---
- name: Install nvm
  shell: |
    set -o pipefail
    curl -o- "{{ nvm_url }}" | /bin/zsh
    creates=$HOME/.nvm/nvm.sh
  args:
    warn: false
  changed_when: false

- name: Install node and set default version
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && nvm install {{ node_version }}
    && nvm alias default {{ node_version }}"
    creates=$HOME/.nvm/alias
  changed_when: false

- name: source zshrc
  become: false
  command: /bin/zsh -c "source ~/.zshrc"
  changed_when: false

- name: Check node versions
  shell: . $HOME/.zshrc && node -v
  args:
    executable: /bin/zsh
  register: node_v
  changed_when: false

- name: Set node versions to fact
  set_fact:
    nvm_node_version: "{{ node_v.stdout }}"

- name: Create a symbolic link to npm
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/npm
    dest: /usr/local/bin/npm
    state: link
    mode: 0644

- name: Create a symbolic link to node
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/node
    dest: /usr/local/bin/node
    state: link
    mode: 0644

- name: Install "protractor" package globally.
  npm:
    name: protractor
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Install "pm2" package globally.
  npm:
    name: pm2
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"
  when: pm2

- name: Create a symbolic link to protractor
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/protractor
    dest: /usr/local/bin/protractor
    state: link
    mode: 0644

- name: Create a symbolic link to webdriver-manager
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/webdriver-manager
    dest: /usr/local/bin/webdriver-manager
    state: link
    mode: 0644
