---
- name: Install docker-compose
  pip:
    name: docker-compose
    executable: /usr/local/bin/pip3
  become: true

- name: Source zshrc
  become: false
  command: /bin/zsh -c "source ~/.zshrc"
  changed_when: false

- name: Start service docker
  become: true
  become_method: sudo
  become_user: "{{ ansible_user }}"
  command: open --background -a Docker
  changed_when: false

- name: Wait until the docker-desktop starts
  wait_for:
    path: /var/run/docker.sock
    state: present

- name: Wait until the docker-desktop daemon.json creates
  wait_for:
    path: $HOME/.docker/daemon.json
    state: present

- name: Add dns settings to docker
  copy:
    content: '{"features":{"buildkit":true},
    "experimental":false,"dns":["8.8.8.8"]}'
    dest: $HOME/.docker/daemon.json
    mode: 0644
